---
version: '2'
services:
  avahi-for-timemachine:
    image: ghcr.io/laszlojau/avahi-for-timemachine
    restart: unless-stopped
    network_mode: host
    ports:  # for reference, not used in host network mode
      - "5353:5353/udp"
